# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: vuepress-deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TARGET_REPO: leonidlezner/leonidlezner.github.io
          TARGET_BRANCH: dist
          BUILD_SCRIPT: yarn && yarn build
          BUILD_DIR: dist

#      - name: Deploy to Github Pages
#        uses: crazy-max/ghaction-github-pages@v2
#        with:
#          target_branch: dist
#          build_dir: dist
#          keep_history: true
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}